
package calculadora.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.1
 * Tue Dec 05 13:20:11 CET 2023
 * Generated source version: 3.6.1
 */

@XmlRootElement(name = "implementacionMO", namespace = "http://calculadora/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "implementacionMO", namespace = "http://calculadora/")

public class ImplementacionMO {


}

