
package calculadora.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.1
 * Tue Dec 05 13:20:11 CET 2023
 * Generated source version: 3.6.1
 */

@XmlRootElement(name = "implementacionGetOperacionesResponse", namespace = "http://calculadora/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "implementacionGetOperacionesResponse", namespace = "http://calculadora/")

public class ImplementacionGetOperacionesResponse {

    @XmlElement(name = "return")
    private String[] _return;

    public String[] getReturn() {
        return this._return;
    }

    public void setReturn(String[] new_return)  {
        this._return = new_return;
    }

}

