
package calculadora;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.6.1
 * 2023-12-05T13:20:13.344+01:00
 * Generated source version: 3.6.1
 *
 */

public class OperacionesCalculadora_PortTypeServer{

    protected OperacionesCalculadora_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new calculadora.OperacionesCalculadora();
        String address = "http://localhost:9090/OperacionesCalculadoraPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new OperacionesCalculadora_PortTypeServer();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}

