package wsCalculadora;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.6.1
 * 2023-12-05T13:38:33.120+01:00
 * Generated source version: 3.6.1
 *
 */
@WebServiceClient(name = "OperacionesCalculadoraService",
                  wsdlLocation = "http://localhost:8080/p3-servidor/services/OperacionesCalculadoraPort?wsdl",
                  targetNamespace = "http://calculadora/")
public class OperacionesCalculadoraService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://calculadora/", "OperacionesCalculadoraService");
    public final static QName OperacionesCalculadoraPort = new QName("http://calculadora/", "OperacionesCalculadoraPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/p3-servidor/services/OperacionesCalculadoraPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OperacionesCalculadoraService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/p3-servidor/services/OperacionesCalculadoraPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OperacionesCalculadoraService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OperacionesCalculadoraService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperacionesCalculadoraService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OperacionesCalculadoraService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OperacionesCalculadoraService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OperacionesCalculadoraService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OperacionesCalculadora
     */
    @WebEndpoint(name = "OperacionesCalculadoraPort")
    public OperacionesCalculadora getOperacionesCalculadoraPort() {
        return super.getPort(OperacionesCalculadoraPort, OperacionesCalculadora.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OperacionesCalculadora
     */
    @WebEndpoint(name = "OperacionesCalculadoraPort")
    public OperacionesCalculadora getOperacionesCalculadoraPort(WebServiceFeature... features) {
        return super.getPort(OperacionesCalculadoraPort, OperacionesCalculadora.class, features);
    }

}
